[2022-12-27T04:50:04.958+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:50:05.000+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:50:05.002+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:50:05.005+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2022-12-27T04:50:05.006+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:50:05.053+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:40:30.365993+00:00
[2022-12-27T04:50:05.070+0000] {standard_task_runner.py:55} INFO - Started process 112 to run task
[2022-12-27T04:50:05.080+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:40:30.365993+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpryh10iju']
[2022-12-27T04:50:05.093+0000] {standard_task_runner.py:83} INFO - Job 376: Subtask extract_test
[2022-12-27T04:50:05.481+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:50:05.979+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:40:30.365993+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:40:30.365993+00:00
[2022-12-27T04:50:05.996+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:50:05.998+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:50:06.000+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:50:06.007+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:50:06.010+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:50:06.011+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 15, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T04:50:06.062+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T044030, start_date=20221227T045004, end_date=20221227T045006
[2022-12-27T04:50:06.118+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 376 for task extract_test (NoBrokersAvailable; 112)
[2022-12-27T04:50:06.188+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:50:06.302+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
