[2022-12-27T04:59:17.579+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:59:11.311569+00:00 [queued]>
[2022-12-27T04:59:17.640+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:59:11.311569+00:00 [queued]>
[2022-12-27T04:59:17.642+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:59:17.645+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-27T04:59:17.647+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:59:17.739+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:59:11.311569+00:00
[2022-12-27T04:59:17.777+0000] {standard_task_runner.py:55} INFO - Started process 428 to run task
[2022-12-27T04:59:17.846+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:59:11.311569+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpim2oiy2f']
[2022-12-27T04:59:17.863+0000] {standard_task_runner.py:83} INFO - Job 379: Subtask extract_test
[2022-12-27T04:59:18.290+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:59:11.311569+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:59:18.780+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:59:11.311569+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:59:11.311569+00:00
[2022-12-27T04:59:18.797+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:59:18.800+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:59:18.810+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Connection complete.
[2022-12-27T04:59:19.140+0000] {conn.py:1106} INFO - Broker version identifed as 1.0.0
[2022-12-27T04:59:19.144+0000] {conn.py:1108} INFO - Set configuration api_version=(1, 0, 0) to skip auto check_version requests on startup
[2022-12-27T04:59:19.197+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('projek_akhir',)
[2022-12-27T04:59:20.328+0000] {logging_mixin.py:137} INFO - Connected
[2022-12-27T04:59:20.332+0000] {streaming.py:185} INFO - Stream connected
[2022-12-27T04:59:24.947+0000] {logging_mixin.py:137} INFO - b'{"text": "RT @SEUNGlNNIE: Ayaka Miyoshi who plays Ann in alice in borderland (who is also a stay) https://t.co/8oan7ZfT2j"}'
[2022-12-27T04:59:24.957+0000] {conn.py:372} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:59:24.959+0000] {conn.py:401} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Connection complete.
[2022-12-27T04:59:24.960+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.25.0.8', 9092)]>: Closing connection. 
[2022-12-27T04:59:25.940+0000] {logging_mixin.py:137} INFO - b'{"text": "the end of alice in borderland s2???????????"}'
[2022-12-27T04:59:29.056+0000] {logging_mixin.py:137} INFO - b'{"text": "RT @neet21_: not Alice in Borderland\'s mangaka randomly running into frame for a split second and yelling \\u201cwhat the hell\\u201d https://t.co/W8OX\\u2026"}'
[2022-12-27T04:59:29.061+0000] {logging_mixin.py:137} INFO - b'{"text": "The very end scene of \\"Alice in Borderland\\" (season 2) was just the icing on an otherwise delicious cake...\\n#Netflix #AliceinBorderland @netflix"}'
[2022-12-27T04:59:29.064+0000] {logging_mixin.py:137} INFO - b'{"text": "RT @zphier_: Alice in borderland s2 ep1 ending without context https://t.co/EthS1bLzFh"}'
[2022-12-27T04:59:32.945+0000] {logging_mixin.py:137} INFO - b'{"text": "bio inspired to what the queen of hearts said on alice in borderland &lt;3"}'
[2022-12-27T04:59:35.087+0000] {logging_mixin.py:137} INFO - b'{"text": "I have yet to watch Alice in borderland \\ud83d\\ude10"}'
[2022-12-27T04:59:35.943+0000] {logging_mixin.py:137} INFO - b'{"text": "Watching Alice In Borderland, it\\u2019s soo mfkin good."}'
[2022-12-27T04:59:39.065+0000] {logging_mixin.py:137} INFO - b'{"text": "RT @kdramatreats: Alice in Borderland 2 outstanding cinematograhy! https://t.co/0iX7dA40WQ"}'
[2022-12-27T04:59:40.087+0000] {logging_mixin.py:137} INFO - b'{"text": "the women in alice in borderland + asugi &amp; chishiya &gt;&gt;&gt;&gt;&gt;&gt;"}'
[2022-12-27T04:59:40.194+0000] {streaming.py:180} ERROR - Stream connection closed by Twitter
[2022-12-27T04:59:40.246+0000] {logging_mixin.py:137} INFO - Disconnected
[2022-12-27T04:59:40.255+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-27T04:59:40.385+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:59:40.571+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Connection complete.
[2022-12-27T04:59:40.808+0000] {cluster.py:376} INFO - Group coordinator for consumers is (1003, 'broker', 9092, None)
[2022-12-27T04:59:40.812+0000] {base.py:688} INFO - Discovered coordinator 1003 for group consumers
[2022-12-27T04:59:40.818+0000] {base.py:735} INFO - Starting new heartbeat thread
[2022-12-27T04:59:40.824+0000] {consumer.py:342} INFO - Revoking previously assigned partitions () for group consumers
[2022-12-27T04:59:40.831+0000] {conn.py:372} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:59:40.941+0000] {conn.py:401} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Connection complete.
[2022-12-27T04:59:40.946+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.25.0.8', 9092)]>: Closing connection. 
[2022-12-27T04:59:41.051+0000] {base.py:447} INFO - (Re-)joining group consumers
[2022-12-27T04:59:41.612+0000] {base.py:516} INFO - Elected group leader -- performing partition assignments using range
[2022-12-27T04:59:42.023+0000] {base.py:333} INFO - Successfully joined group consumers with generation 7
[2022-12-27T04:59:42.057+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('projek_akhir', 0)]
[2022-12-27T04:59:42.064+0000] {consumer.py:239} INFO - Setting newly assigned partitions (('projek_akhir', 0),) for group consumers
[2022-12-27T04:59:42.506+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 320, in read_sql_table
    meta.reflect(only=[table_name], views=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4891, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(postgresql+psycopg2://***:***@postgres:5432/***): (tweets)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 109, in start_etl
    datasql = pd.read_sql_table('tweets', engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 322, in read_sql_table
    raise ValueError(f"Table {table_name} not found") from err
ValueError: Table tweets not found
[2022-12-27T04:59:42.688+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T045911, start_date=20221227T045917, end_date=20221227T045942
[2022-12-27T04:59:42.968+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 379 for task extract_test (Table tweets not found; 428)
[2022-12-27T04:59:43.288+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:59:44.074+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
